name: Deploy Pocketbase

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']
    paths: ['pocketbase/**', '.github/**']

jobs:
  fly-deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-db # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: pocketbase
        env:
          FLY_API_TOKEN: ${{ secrets.POCKETBASE_FLY_API_TOKEN }}

      - name: Send pushover notification
        run: |
          curl -s \
          --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
          --form-string "user=${{ secrets.PUSHOVER_USER }}" \
          --form-string "message=dynogee-pocketbase: deploy completed." \
          https://api.pushover.net/1/messages.json
