name: E2E Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./site

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ctxs_dev
          POSTGRES_PASSWORD: ctxs_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium

      - name: Build project
        run: bun run build

      - name: Run Playwright tests
        run: bun run test
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          BETTER_AUTH_SECRET: "foobar"
          DATABASE_URL: postgresql://ctxs_dev:ctxs_dev@localhost:5432/ctxs_dev

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
