name: E2E Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ctxs_dev
          POSTGRES_PASSWORD: ctxs_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpx playwright install --with-deps chromium

      - name: Build project
        run: pnpm -r build

      - name: Migrate DB
        run: pnpm -r push
        env:
          DATABASE_URL: postgresql://ctxs_dev:ctxs_dev@localhost:5432/ctxs_dev

      - name: Start services
        run: |
          pnpm --filter workflows dev &
          pnpm --filter web preview &

      - name: Run Playwright tests
        run: pnpm run test
        working-directory: apps/web
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          CF_ENDPOINT: 'http://localhost:8787'
          CF_API_KEY: 'wrong'
          BETTER_AUTH_SECRET: 'foobar'
          DATABASE_URL: postgresql://ctxs_dev:ctxs_dev@localhost:5432/ctxs_dev

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
